# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jeremy/projects/mldb-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jeremy/projects/mldb-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeremy/projects/mldb-master/CMakeFiles /Users/jeremy/projects/mldb-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeremy/projects/mldb-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arch

# Build rule for target.
arch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arch
.PHONY : arch

# fast build rule for target.
arch/fast:
	$(MAKE) $(MAKESILENT) -f arch/CMakeFiles/arch.dir/build.make arch/CMakeFiles/arch.dir/build
.PHONY : arch/fast

#=============================================================================
# Target rules for targets named gc

# Build rule for target.
gc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gc
.PHONY : gc

# fast build rule for target.
gc/fast:
	$(MAKE) $(MAKESILENT) -f arch/CMakeFiles/gc.dir/build.make arch/CMakeFiles/gc.dir/build
.PHONY : gc/fast

#=============================================================================
# Target rules for targets named exception_hook

# Build rule for target.
exception_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exception_hook
.PHONY : exception_hook

# fast build rule for target.
exception_hook/fast:
	$(MAKE) $(MAKESILENT) -f arch/CMakeFiles/exception_hook.dir/build.make arch/CMakeFiles/exception_hook.dir/build
.PHONY : exception_hook/fast

#=============================================================================
# Target rules for targets named bitops_test

# Build rule for target.
bitops_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitops_test
.PHONY : bitops_test

# fast build rule for target.
bitops_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/bitops_test.dir/build.make arch/testing/CMakeFiles/bitops_test.dir/build
.PHONY : bitops_test/fast

#=============================================================================
# Target rules for targets named wait_on_address_test

# Build rule for target.
wait_on_address_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wait_on_address_test
.PHONY : wait_on_address_test

# fast build rule for target.
wait_on_address_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/wait_on_address_test.dir/build.make arch/testing/CMakeFiles/wait_on_address_test.dir/build
.PHONY : wait_on_address_test/fast

#=============================================================================
# Target rules for targets named fslock_test

# Build rule for target.
fslock_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fslock_test
.PHONY : fslock_test

# fast build rule for target.
fslock_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/fslock_test.dir/build.make arch/testing/CMakeFiles/fslock_test.dir/build
.PHONY : fslock_test/fast

#=============================================================================
# Target rules for targets named simd_vector_test

# Build rule for target.
simd_vector_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simd_vector_test
.PHONY : simd_vector_test

# fast build rule for target.
simd_vector_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/simd_vector_test.dir/build.make arch/testing/CMakeFiles/simd_vector_test.dir/build
.PHONY : simd_vector_test/fast

#=============================================================================
# Target rules for targets named simd_vector_benchmark

# Build rule for target.
simd_vector_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simd_vector_benchmark
.PHONY : simd_vector_benchmark

# fast build rule for target.
simd_vector_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/simd_vector_benchmark.dir/build.make arch/testing/CMakeFiles/simd_vector_benchmark.dir/build
.PHONY : simd_vector_benchmark/fast

#=============================================================================
# Target rules for targets named backtrace_test

# Build rule for target.
backtrace_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 backtrace_test
.PHONY : backtrace_test

# fast build rule for target.
backtrace_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/backtrace_test.dir/build.make arch/testing/CMakeFiles/backtrace_test.dir/build
.PHONY : backtrace_test/fast

#=============================================================================
# Target rules for targets named bit_range_ops_test

# Build rule for target.
bit_range_ops_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bit_range_ops_test
.PHONY : bit_range_ops_test

# fast build rule for target.
bit_range_ops_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/bit_range_ops_test.dir/build.make arch/testing/CMakeFiles/bit_range_ops_test.dir/build
.PHONY : bit_range_ops_test/fast

#=============================================================================
# Target rules for targets named info_test

# Build rule for target.
info_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 info_test
.PHONY : info_test

# fast build rule for target.
info_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/info_test.dir/build.make arch/testing/CMakeFiles/info_test.dir/build
.PHONY : info_test/fast

#=============================================================================
# Target rules for targets named rtti_utils_test

# Build rule for target.
rtti_utils_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtti_utils_test
.PHONY : rtti_utils_test

# fast build rule for target.
rtti_utils_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/rtti_utils_test.dir/build.make arch/testing/CMakeFiles/rtti_utils_test.dir/build
.PHONY : rtti_utils_test/fast

#=============================================================================
# Target rules for targets named thread_specific_test

# Build rule for target.
thread_specific_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thread_specific_test
.PHONY : thread_specific_test

# fast build rule for target.
thread_specific_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/thread_specific_test.dir/build.make arch/testing/CMakeFiles/thread_specific_test.dir/build
.PHONY : thread_specific_test/fast

#=============================================================================
# Target rules for targets named gc_test

# Build rule for target.
gc_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gc_test
.PHONY : gc_test

# fast build rule for target.
gc_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/gc_test.dir/build.make arch/testing/CMakeFiles/gc_test.dir/build
.PHONY : gc_test/fast

#=============================================================================
# Target rules for targets named shared_gc_lock_test

# Build rule for target.
shared_gc_lock_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared_gc_lock_test
.PHONY : shared_gc_lock_test

# fast build rule for target.
shared_gc_lock_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/shared_gc_lock_test.dir/build.make arch/testing/CMakeFiles/shared_gc_lock_test.dir/build
.PHONY : shared_gc_lock_test/fast

#=============================================================================
# Target rules for targets named rcu_protected_test

# Build rule for target.
rcu_protected_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rcu_protected_test
.PHONY : rcu_protected_test

# fast build rule for target.
rcu_protected_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/rcu_protected_test.dir/build.make arch/testing/CMakeFiles/rcu_protected_test.dir/build
.PHONY : rcu_protected_test/fast

#=============================================================================
# Target rules for targets named tick_counter_test

# Build rule for target.
tick_counter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tick_counter_test
.PHONY : tick_counter_test

# fast build rule for target.
tick_counter_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/tick_counter_test.dir/build.make arch/testing/CMakeFiles/tick_counter_test.dir/build
.PHONY : tick_counter_test/fast

#=============================================================================
# Target rules for targets named bit_array_test

# Build rule for target.
bit_array_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bit_array_test
.PHONY : bit_array_test

# fast build rule for target.
bit_array_test/fast:
	$(MAKE) $(MAKESILENT) -f arch/testing/CMakeFiles/bit_array_test.dir/build.make arch/testing/CMakeFiles/bit_array_test.dir/build
.PHONY : bit_array_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arch"
	@echo "... backtrace_test"
	@echo "... bit_array_test"
	@echo "... bit_range_ops_test"
	@echo "... bitops_test"
	@echo "... exception_hook"
	@echo "... fslock_test"
	@echo "... gc"
	@echo "... gc_test"
	@echo "... info_test"
	@echo "... rcu_protected_test"
	@echo "... rtti_utils_test"
	@echo "... shared_gc_lock_test"
	@echo "... simd_vector_benchmark"
	@echo "... simd_vector_test"
	@echo "... thread_specific_test"
	@echo "... tick_counter_test"
	@echo "... wait_on_address_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

