$(eval $(call mldb_unit_test,get_all_column_names.py))
$(eval $(call mldb_unit_test,value_and_ts_in_cell.py))
$(eval $(call mldb_unit_test,timediff_in_seconds.py))
$(eval $(call mldb_unit_test,threading_example.py,,manual))
$(eval $(call mldb_unit_test,mldb_logging_stream_handler.py))
